apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: challengespringbootgraylog-mongo-data-graylog
  name: challengespringbootgraylog-mongo-data-graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
