apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: challengespringbootgraylog-graylog-journal
  name: challengespringbootgraylog-graylog-journal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
