apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: challengespringbootgraylog-es-data
  name: challengespringbootgraylog-es-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
