apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mongodb-graylog
  name: mongodb-graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-graylog
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      labels:
        io.kompose.service: mongodb-graylog
    spec:
      containers:
        - image: mongo:3
          name: mongodb-graylog
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db_graylog_1
              name: challengespringbootgraylog-mongo-data-graylog
      restartPolicy: Always
      volumes:
        - name: challengespringbootgraylog-mongo-data-graylog
          persistentVolumeClaim:
            claimName: challengespringbootgraylog-mongo-data-graylog
