apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  labels:
    io.kompose.service: mongodb-graylog
  name: mongo
  namespace: graylog
spec:
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    io.kompose.service: mongodb-graylog
  sessionAffinity: None
  type: ClusterIP

